blueprint:
  name: Apollo Air Sensor Notification
  description: >
    This blueprint monitors values from Apollo Air sensors and sends a notification if any values exceed the defined thresholds.
  domain: automation
  input:
    temperature_settings:
      name: Temperature
      icon: mdi:thermometer
      collapsed: true
      input:
        temperature_sensor:
          name: Temperature Sensor
          description: "Select the temperature sensor."
          default: null
          selector:
            entity:
              integration: esphome
              domain: sensor
              device_class: temperature
        min_temp:
          name: Minimum Temperature
          description: "Set the minimum acceptable temperature (°C)."
          default: 15
          selector:
            number:
              min: -10
              max: 50
              unit_of_measurement: °C
        max_temp:
          name: Maximum Temperature
          description: "Set the maximum acceptable temperature (°C)."
          default: 30
          selector:
            number:
              min: -10
              max: 50
              unit_of_measurement: °C

variables:
  temperature_sensor: !input temperature_sensor
  min_temp: !input min_temp
  max_temp: !input max_temp

trigger:
- platform: numeric_state
  entity_id: !input temperature_sensor
  above: !input max_temp
- platform: numeric_state
  entity_id: !input temperature_sensor
  below: !input min_temp

action:
- service: notify.notify
  data:
    title: "Temperature Alert"
    message: >
      {% if trigger.above %}
        The temperature is {{ states(temperature_sensor) }}°C which is above the maximum threshold of {{ max_temp }}°C.
      {% else %}
        The temperature is {{ states(temperature_sensor) }}°C which is below the minimum threshold of {{ min_temp }}°C.
      {% endif %}
